### ISSUE TITLE
Using info.save() creates a copy of the original

### ISSUE THREAD

**Issue by Clonimus74** [jamesacampbell/iptcinfo3#22]
When I use info.save() I assume it will overwrite the original, but it also makes a backup of it.
I don't know if it is by design, but when using this to batch tag many images it is undesirable.

I see that it happens at lines 689-690

`            if os.path.exists(newfile):
                shutil.move(newfile, newfile + '~')
`

**Comment by wlockwood** [comment]
I've hit this as well and was really hoping there would be an override somewhere. Seems to violate the principle of least surprise.

**Comment by jamesacampbell** [comment]
resolved by #29
